Dev 2ex
ArtemKarablinov/made_2019_algo pull request #2
Opened 2019-11-09 16:48 UTC by ArtemKarablinov

Второе дз. 
Задачи 3_2 и 4_2. 
Посылки на Я.Контест:
3_2: https://contest.yandex.ru/contest/14768/run-report/23854005/
4_2: https://contest.yandex.ru/contest/14768/run-report/23860630/

2019-11-12 22:27 UTC, ylyubimov requested changes
В будущем одна задача, один ПР

2019-11-12 22:27 UTC, ylyubimov commented on 02/hw2_Ex3_2.cpp
> +void MergeSort(int* a, int start,  int end){
Сделай сортировку шаблонной и добавь класс компаратор
template <class T, class TLess>
void MergeSort(T* a, int start ,int end, TLess is_less)

2019-11-12 22:27 UTC, ylyubimov commented on 02/hw2_Ex4_2.cpp
> +int Partition(int* a, int size){
Тоже шаблон + функция сравнения

2019-11-12 22:28 UTC, ylyubimov requested changes
Читай выше

2019-11-12 22:29 UTC, ylyubimov requested changes
Переделай и призови ревьювером по новой

2019-11-12 22:29 UTC, ylyubimov commented
Наверное нужно меня сделать коллаборатором в репозитории

2019-12-12 20:29 UTC, ArtemKarablinov commented on 02/hw2_Ex3_2.cpp
> +void MergeSort(int* a, int start,  int end){
done

2019-12-12 20:29 UTC, ArtemKarablinov commented on 02/hw2_Ex4_2.cpp
> +int Partition(int* a, int size){
done

2019-12-12 20:29 UTC, ArtemKarablinov commented
@ylyubimov Все замечания учтены

2019-12-28 12:09 UTC, ylyubimov approved these changes

2019-12-28 15:48 UTC, merged