3hw 6 2
ArtemKarablinov/made_2019_algo pull request #3
Opened 2019-11-27 21:02 UTC by ArtemKarablinov

Ссылки на посылки:
задача 6_2
https://contest.yandex.ru/contest/15368/run-report/26474614/
Дополнительно сделал 6_1
https://contest.yandex.ru/contest/15368/run-report/26403616/

2019-12-04 22:46 UTC, ylyubimov requested changes

2019-12-04 22:46 UTC, ylyubimov commented on 03/3hw-6_2.cpp
> +        ~Tree(){};
Правило 5ти

2019-12-04 22:46 UTC, ylyubimov commented on 03/3hw-6_2.cpp
> +        void inorder_print();
inorder/preorder методы должны быть const

2019-12-04 22:46 UTC, ylyubimov commented on 03/3hw-6_2.cpp
> +        void inorder_print();
+ они должны не просто печатать, а делать произвольные вещи с элементами, которые захотел пользователь
```
template <class TVisitor> 
void in_order(const TVisitor& visit) const
```

2019-12-04 22:46 UTC, ylyubimov commented on 03/3hw-6_2.cpp
> +        ~Tree(){};
Плюс очень странный деструктор, как освобождается память?

2019-12-04 22:46 UTC, ylyubimov commented on 03/3hw-6_2.cpp
> +        ~Tree(){};
Можно кстати просто вызвать какой-нибудь обход с правильной функцией
preorder([](const Node* node){delete node;});

2019-12-11 20:27 UTC, ArtemKarablinov commented on 03/3hw-6_2.cpp
> +        ~Tree(){};
done

2019-12-11 20:27 UTC, ArtemKarablinov commented on 03/3hw-6_2.cpp
> +        void inorder_print();
done

2019-12-11 20:27 UTC, ArtemKarablinov commented
@ylyubimov Верно ли исправил замечания?

2019-12-28 12:07 UTC, ylyubimov requested changes

2019-12-28 12:07 UTC, ylyubimov commented on 03/3hw-6_2.cpp
> +void Tree<T>::inorder_print(Node<T>* root) const{
Хотелось бы функцию вида
template<typename T, template TVisitor>
void Tree<T>::inorder(Node<T>* root, const TVisitor& visit)
А внутри нее в нужом месте
visit(node); 
Тогда ты сможешь написать
inorder(root, [](const Node* node){ std::cout << node->Value << std::endl; }) - для печати

inorder(root, [](const Node* node){ delete node; }) - для удаления

2020-01-09 13:46 UTC, ArtemKarablinov commented on 03/3hw-6_2.cpp
> +void Tree<T>::inorder_print(Node<T>* root) const{
сделал через callback  - получилось для печати и удаления так как вы написали

2020-01-13 22:26 UTC, ylyubimov approved these changes
Не совсем то, что я хотел, но ладно

2020-01-15 16:37 UTC, merged